//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewYorkUtilities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public decimal Id { get; set; }
        public Nullable<int> Category { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SiteLink { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Pincode { get; set; }
    }
}
